title: Boris Baic # your name (or website title) here
logo: "/images/Profi.jpg?raw=false" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Game Developer:
  - Unity C#
  <br><br>
  Pravni fakultet Osijek
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
